// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOwmMaqY6v07KCUHPvrfWZC0PTbAG_6M',
    appId: '1:185195273192:web:14a06ab8cfbd9daa2d225d',
    messagingSenderId: '185195273192',
    projectId: 'messanger-app-ad524',
    authDomain: 'messanger-app-ad524.firebaseapp.com',
    storageBucket: 'messanger-app-ad524.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyV37s6_HgWAEprwMhdRFUoSnO-rtC78',
    appId: '1:185195273192:android:84720879956d83852d225d',
    messagingSenderId: '185195273192',
    projectId: 'messanger-app-ad524',
    storageBucket: 'messanger-app-ad524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQWTitwsojry4_6UCZWNPLKPe72yCF1c',
    appId: '1:185195273192:ios:bdb37fd6a123d5052d225d',
    messagingSenderId: '185195273192',
    projectId: 'messanger-app-ad524',
    storageBucket: 'messanger-app-ad524.appspot.com',
    iosClientId: '185195273192-286dht4dcuanv3ta34eb8re6e384ao77.apps.googleusercontent.com',
    iosBundleId: 'com.example.messangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQWTitwsojry4_6UCZWNPLKPe72yCF1c',
    appId: '1:185195273192:ios:bdb37fd6a123d5052d225d',
    messagingSenderId: '185195273192',
    projectId: 'messanger-app-ad524',
    storageBucket: 'messanger-app-ad524.appspot.com',
    iosClientId: '185195273192-286dht4dcuanv3ta34eb8re6e384ao77.apps.googleusercontent.com',
    iosBundleId: 'com.example.messangerApp',
  );
}
